/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProfileResponse {
  avatar_key?: string | null;
  created_at: string;
  display_name?: string | null;
  id: string;
  role: string;
  theme_preference?: string | null;
  username: string;
}
