/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectResponse {
  created_at: string;
  duration_seconds?: number | null;
  id: string;
  started_at?: string | null;
  status?: string;
  title: string;
  updated_at: string;
  user_id: string;
}
