/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Token {
  access_token: string;
  email: string;
  refresh_token: string;
  role: string;
  token_type?: string;
  user_id: string;
  username: string;
}
