/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProfileResponse } from '../models/profile-response';
export interface UserResponse {
  created_at: string;
  disabled_at?: string | null;
  email: string;
  id: string;
  profile?: ProfileResponse | null;
}
