/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { ApiConfiguration } from '../api-configuration';
import { BaseService } from '../base-service';
import { StrictHttpResponse } from '../strict-http-response';

import {
  geminiCheckGeminiGet,
  GeminiCheckGeminiGet$Params,
} from '../fn/operations/gemini-check-gemini-get';
import {
  healthCheckHealthGet,
  HealthCheckHealthGet$Params,
} from '../fn/operations/health-check-health-get';
import { readRootGet, ReadRootGet$Params } from '../fn/operations/read-root-get';
import {
  speechmaticsCheckSpeechmaticsGet,
  SpeechmaticsCheckSpeechmaticsGet$Params,
} from '../fn/operations/speechmatics-check-speechmatics-get';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `readRootGet()` */
  static readonly ReadRootGetPath = '/';

  /**
   * Read Root.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `readRootGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  readRootGet$Response(
    params?: ReadRootGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<any>> {
    const obs = readRootGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Read Root.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `readRootGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  readRootGet(params?: ReadRootGet$Params, context?: HttpContext): Observable<any> {
    const resp = this.readRootGet$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<any>): any => r.body));
  }

  /** Path part for operation `healthCheckHealthGet()` */
  static readonly HealthCheckHealthGetPath = '/health';

  /**
   * Health Check.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `healthCheckHealthGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthCheckHealthGet$Response(
    params?: HealthCheckHealthGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<any>> {
    const obs = healthCheckHealthGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Health Check.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `healthCheckHealthGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthCheckHealthGet(
    params?: HealthCheckHealthGet$Params,
    context?: HttpContext,
  ): Observable<any> {
    const resp = this.healthCheckHealthGet$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<any>): any => r.body));
  }

  /** Path part for operation `geminiCheckGeminiGet()` */
  static readonly GeminiCheckGeminiGetPath = '/gemini';

  /**
   * Gemini Check.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `geminiCheckGeminiGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  geminiCheckGeminiGet$Response(
    params?: GeminiCheckGeminiGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<any>> {
    const obs = geminiCheckGeminiGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Gemini Check.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `geminiCheckGeminiGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  geminiCheckGeminiGet(
    params?: GeminiCheckGeminiGet$Params,
    context?: HttpContext,
  ): Observable<any> {
    const resp = this.geminiCheckGeminiGet$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<any>): any => r.body));
  }

  /** Path part for operation `speechmaticsCheckSpeechmaticsGet()` */
  static readonly SpeechmaticsCheckSpeechmaticsGetPath = '/speechmatics';

  /**
   * Speechmatics Check.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `speechmaticsCheckSpeechmaticsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  speechmaticsCheckSpeechmaticsGet$Response(
    params?: SpeechmaticsCheckSpeechmaticsGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<any>> {
    const obs = speechmaticsCheckSpeechmaticsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Speechmatics Check.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `speechmaticsCheckSpeechmaticsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  speechmaticsCheckSpeechmaticsGet(
    params?: SpeechmaticsCheckSpeechmaticsGet$Params,
    context?: HttpContext,
  ): Observable<any> {
    const resp = this.speechmaticsCheckSpeechmaticsGet$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<any>): any => r.body));
  }
}
