/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { ApiConfiguration } from '../api-configuration';
import { BaseService } from '../base-service';
import { StrictHttpResponse } from '../strict-http-response';

import {
  loginAuthLoginPost,
  LoginAuthLoginPost$Params,
} from '../fn/authentication/login-auth-login-post';
import {
  logoutAuthLogoutPost,
  LogoutAuthLogoutPost$Params,
} from '../fn/authentication/logout-auth-logout-post';
import {
  refreshTokenAuthRefreshPost,
  RefreshTokenAuthRefreshPost$Params,
} from '../fn/authentication/refresh-token-auth-refresh-post';
import {
  registerAuthRegisterPost,
  RegisterAuthRegisterPost$Params,
} from '../fn/authentication/register-auth-register-post';
import { LogoutResponse } from '../models/logout-response';
import { RegisterResponse } from '../models/register-response';
import { Token } from '../models/token';
import { TokenRefreshResponse } from '../models/token-refresh-response';

@Injectable({ providedIn: 'root' })
export class AuthenticationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registerAuthRegisterPost()` */
  static readonly RegisterAuthRegisterPostPath = '/auth/register';

  /**
   * Register.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerAuthRegisterPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerAuthRegisterPost$Response(
    params: RegisterAuthRegisterPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<RegisterResponse>> {
    const obs = registerAuthRegisterPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Register.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerAuthRegisterPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerAuthRegisterPost(
    params: RegisterAuthRegisterPost$Params,
    context?: HttpContext,
  ): Observable<RegisterResponse> {
    const resp = this.registerAuthRegisterPost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<RegisterResponse>): RegisterResponse => r.body));
  }

  /** Path part for operation `loginAuthLoginPost()` */
  static readonly LoginAuthLoginPostPath = '/auth/login';

  /**
   * Login.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `loginAuthLoginPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  loginAuthLoginPost$Response(
    params: LoginAuthLoginPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Token>> {
    const obs = loginAuthLoginPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Login.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `loginAuthLoginPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  loginAuthLoginPost(params: LoginAuthLoginPost$Params, context?: HttpContext): Observable<Token> {
    const resp = this.loginAuthLoginPost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<Token>): Token => r.body));
  }

  /** Path part for operation `refreshTokenAuthRefreshPost()` */
  static readonly RefreshTokenAuthRefreshPostPath = '/auth/refresh';

  /**
   * Refresh Token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `refreshTokenAuthRefreshPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refreshTokenAuthRefreshPost$Response(
    params: RefreshTokenAuthRefreshPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<TokenRefreshResponse>> {
    const obs = refreshTokenAuthRefreshPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Refresh Token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `refreshTokenAuthRefreshPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refreshTokenAuthRefreshPost(
    params: RefreshTokenAuthRefreshPost$Params,
    context?: HttpContext,
  ): Observable<TokenRefreshResponse> {
    const resp = this.refreshTokenAuthRefreshPost$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<TokenRefreshResponse>): TokenRefreshResponse => r.body),
    );
  }

  /** Path part for operation `logoutAuthLogoutPost()` */
  static readonly LogoutAuthLogoutPostPath = '/auth/logout';

  /**
   * Logout.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `logoutAuthLogoutPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  logoutAuthLogoutPost$Response(
    params?: LogoutAuthLogoutPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<LogoutResponse>> {
    const obs = logoutAuthLogoutPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Logout.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `logoutAuthLogoutPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  logoutAuthLogoutPost(
    params?: LogoutAuthLogoutPost$Params,
    context?: HttpContext,
  ): Observable<LogoutResponse> {
    const resp = this.logoutAuthLogoutPost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<LogoutResponse>): LogoutResponse => r.body));
  }
}
