/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { ApiConfiguration } from '../api-configuration';
import { BaseService } from '../base-service';
import { StrictHttpResponse } from '../strict-http-response';

import {
  listUserProjectsProjectsGet,
  ListUserProjectsProjectsGet$Params,
} from '../fn/projects-by-user/list-user-projects-projects-get';
import { ProjectResponse } from '../models/project-response';

@Injectable({ providedIn: 'root' })
export class ProjectsByUserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listUserProjectsProjectsGet()` */
  static readonly ListUserProjectsProjectsGetPath = '/projects';

  /**
   * List User Projects.
   *
   * Get the list of projects (meetings) belonging to the authenticated user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listUserProjectsProjectsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  listUserProjectsProjectsGet$Response(
    params?: ListUserProjectsProjectsGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<ProjectResponse>>> {
    const obs = listUserProjectsProjectsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List User Projects.
   *
   * Get the list of projects (meetings) belonging to the authenticated user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listUserProjectsProjectsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listUserProjectsProjectsGet(
    params?: ListUserProjectsProjectsGet$Params,
    context?: HttpContext,
  ): Observable<Array<ProjectResponse>> {
    const resp = this.listUserProjectsProjectsGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ProjectResponse>>): Array<ProjectResponse> => r.body),
    );
  }
}
