/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { ApiConfiguration } from '../api-configuration';
import { BaseService } from '../base-service';
import { StrictHttpResponse } from '../strict-http-response';

import {
  getUserDetailAdminUsersIdGet,
  GetUserDetailAdminUsersIdGet$Params,
} from '../fn/user-management/get-user-detail-admin-users-id-get';
import {
  listUsersAdminUsersGet,
  ListUsersAdminUsersGet$Params,
} from '../fn/user-management/list-users-admin-users-get';
import { UserResponse } from '../models/user-response';

@Injectable({ providedIn: 'root' })
export class UserManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listUsersAdminUsersGet()` */
  static readonly ListUsersAdminUsersGetPath = '/admin/users';

  /**
   * List Users.
   *
   * Admin-only endpoint to list all users, with pagination and optional role filtering.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listUsersAdminUsersGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  listUsersAdminUsersGet$Response(
    params?: ListUsersAdminUsersGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<UserResponse>>> {
    const obs = listUsersAdminUsersGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List Users.
   *
   * Admin-only endpoint to list all users, with pagination and optional role filtering.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listUsersAdminUsersGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listUsersAdminUsersGet(
    params?: ListUsersAdminUsersGet$Params,
    context?: HttpContext,
  ): Observable<Array<UserResponse>> {
    const resp = this.listUsersAdminUsersGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<UserResponse>>): Array<UserResponse> => r.body),
    );
  }

  /** Path part for operation `getUserDetailAdminUsersIdGet()` */
  static readonly GetUserDetailAdminUsersIdGetPath = '/admin/users/{id}';

  /**
   * Get User Detail.
   *
   * Admin-only endpoint to retrieve user account and profile details.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserDetailAdminUsersIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserDetailAdminUsersIdGet$Response(
    params: GetUserDetailAdminUsersIdGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<UserResponse>> {
    const obs = getUserDetailAdminUsersIdGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get User Detail.
   *
   * Admin-only endpoint to retrieve user account and profile details.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserDetailAdminUsersIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserDetailAdminUsersIdGet(
    params: GetUserDetailAdminUsersIdGet$Params,
    context?: HttpContext,
  ): Observable<UserResponse> {
    const resp = this.getUserDetailAdminUsersIdGet$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body));
  }
}
