/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

import { ProjectResponse } from '../../models/project-response';

export interface ListUserProjectsProjectsGet$Params {
  skip?: number;
  limit?: number;
}

export function listUserProjectsProjectsGet(
  http: HttpClient,
  rootUrl: string,
  params?: ListUserProjectsProjectsGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<ProjectResponse>>> {
  const rb = new RequestBuilder(rootUrl, listUserProjectsProjectsGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProjectResponse>>;
    }),
  );
}

listUserProjectsProjectsGet.PATH = '/projects';
