/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

import { LogoutResponse } from '../../models/logout-response';

export interface LogoutAuthLogoutPost$Params {}

export function logoutAuthLogoutPost(
  http: HttpClient,
  rootUrl: string,
  params?: LogoutAuthLogoutPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<LogoutResponse>> {
  const rb = new RequestBuilder(rootUrl, logoutAuthLogoutPost.PATH, 'post');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LogoutResponse>;
    }),
  );
}

logoutAuthLogoutPost.PATH = '/auth/logout';
