/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

import { RefreshTokenRequest } from '../../models/refresh-token-request';
import { TokenRefreshResponse } from '../../models/token-refresh-response';

export interface RefreshTokenAuthRefreshPost$Params {
  body: RefreshTokenRequest;
}

export function refreshTokenAuthRefreshPost(
  http: HttpClient,
  rootUrl: string,
  params: RefreshTokenAuthRefreshPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<TokenRefreshResponse>> {
  const rb = new RequestBuilder(rootUrl, refreshTokenAuthRefreshPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TokenRefreshResponse>;
    }),
  );
}

refreshTokenAuthRefreshPost.PATH = '/auth/refresh';
