/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

import { RegisterRequest } from '../../models/register-request';
import { RegisterResponse } from '../../models/register-response';

export interface RegisterAuthRegisterPost$Params {
  body: RegisterRequest;
}

export function registerAuthRegisterPost(
  http: HttpClient,
  rootUrl: string,
  params: RegisterAuthRegisterPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<RegisterResponse>> {
  const rb = new RequestBuilder(rootUrl, registerAuthRegisterPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegisterResponse>;
    }),
  );
}

registerAuthRegisterPost.PATH = '/auth/register';
